### ISSUE TITLE
Пункт "Настроить mmagent" - неправильно определяет тип диска

### ISSUE THREAD

**Issue by FedorAdo** [Vijorich/Uber-cleaner#1]
Собственно, выбираю этот пункт и получаю - "Настроено для hdd!"
Но у меня SSD.
Команда `smartctl.exe -i C:` выдаёт

> Read Device Identity failed: Input/output error
> If this is a USB connected device, look at the various --device=TYPE variants
> A mandatory SMART command failed: exiting. To continue, add one or more '-T permissive' options.

Windows 11.

**Comment by Vijorich** [comment]
@FedorAdo Почитал по этому поводу, попробуйте обновить драйвера/прошивку вашего ssd, так же можете проверить состояние S.M.A.R.T через программу производителя, либо любую другую, например GSmartControl.
В следующей версии добавлю сообщение об ошибке и просьбу проверить состояние своего SSD, после которого будет уже ручной выбор SSD или HDD.

**Comment by Vijorich** [comment]
@FedorAdo 
Добавил проверку на ошибки, прошу проверить работоспособность.

**Comment by FedorAdo** [comment]
> @FedorAdo Добавил проверку на ошибки, прошу проверить работоспособность.

![image](https://user-images.githubusercontent.com/30267668/220379564-a8127348-6f4e-471a-ab5a-8464dd7a6091.png)
Спасибо. Теперь отлично. Успехов.
